name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Prettier
        run: if [ "$(node_modules/.bin/prettier --list-different "**/*.{js,jsx,ts,tsx,json}")" ]; then echo "Prettier failed" exit 1; fi

      - name: ESLint
        run: yarn lint

      - name: Trigger GitHub pages rebuild
        run: |
          curl --fail --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/pages/builds \
            --header "Authorization: Bearer $STUDY4IT_ACCESS_TOKEN"
        env:
          STUDY4IT_ACCESS_TOKEN: ${{ secrets.STUDY4IT_ACCESS_TOKEN }}
