name: CI/CD

on:
  push:
    branches: [ master ]

jobs:
  workflow:
    runs-on: ubuntu-latest

    if: startsWith(github.event.comment.body, 'Publish to GitHub Pages') == false

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Prettier
        run: if [ "$(node_modules/.bin/prettier --list-different "**/*.{js,jsx,ts,tsx,json}")" ]; then echo "Prettier failed" exit 1; fi

      - name: ESLint
        run: yarn lint

      - name: Export
        run: yarn export

      - name: Commit and Push to GitHub
        run: |
          echo https://${STUDY4IT_ACCESS_TOKEN}:x-oauth-basic@github.com>> ${HOME}/.git-credentials
          git config --global user.email "study4it@mail.ru"
          git config --global user.name "study4it"
          git add .
          git commit -m 'Publish to GitHub Pages' --allow-empty
          git push origin master
        env:
          STUDY4IT_ACCESS_TOKEN: ${{ secrets.STUDY4IT_ACCESS_TOKEN }}
